apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "injector-controller.fullname" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "injector-controller.fullname" . }}
webhooks:
  - name: io.k8s.{{ include "injector-controller.fullname" . }}
    objectSelector:
      matchExpressions:
        - key: "app.kubernetes.io/name"
          operator: NotIn
          values: ["{{ include "injector-controller.fullname" . }}"]
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "injector-controller.fullname" . }}
        path: /mutate
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10
